baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Abhishek's Tech Blog"
theme = "custom-theme"

paginate = 10
enableRobotsTXT = true

[params]
  author = "Abhishek Chourasia"
  description = "Frontend Engineering Blog"

[taxonomies]
  category = "categories"
  author = "authors"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true